# Update project files and submit a PR with the results.

name: "Update files using tools"

on:
  workflow_dispatch: {}
  schedule:
    # Run at 04:32 UTC on Mondays.
    - cron: "32 4 * * 1"

jobs:
  update:
    name: "Update"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.8"

      - id: update
        shell: bash
        run: |
          python -m pip install upadup
          upadup

          if [[ -z "$(git status --porcelain)" ]]; then
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi

      - if: ${{ steps.update.outputs.changes_exist == 'true' }}
        shell: bash
        run: |
          echo "yes"
