# Update project files and submit a PR with the results.

name: "Update files using tools"

on:
  workflow_dispatch: {}
  schedule:
    # Run at 04:32 UTC on Mondays.
    - cron: "32 4 * * 1"

jobs:
  update:
    name: "Update"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v3"

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.8"

      - name: "Install upadup"
        run: "python -m pip install upadup"

      - name: "Run upadup"
        run: "upadup"

      - name: "Detect changes"
        id: "detector"
        shell: "bash"
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi

      - name: "Create pull request"
        if: "${{ steps.detector.outputs.changes_exist == 'true' }}"
        shell: "bash"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          git config --global user.email "contactme@kurtmckee.org"
          git config --global user.name "Kurt McKee"

          git checkout -b update-additional_dependencies
          git commit -am "Update additional_dependencies"
          git push origin --set-upstream update-additional_dependencies

          gh pr create --title "Update additional_dependencies" --body ""
